
---
# tasks file for mariadb
      
    - name: creates database for wordpress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "rrrr"

    - name: create mysql user for wordpress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "rrrr"
